config/routes.rb
Rails.application.routes.draw do
  resources :events do 
    collection do
      post :accept
      delete :reject
    end
  end
  root to: 'dashboard#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees,  :dependent => :destroy
  has_many :users, through: :attendees

  validates :title, presence: true, uniqueness: true
  validates :start_date, presence: true
  validates :venue, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :attendees, :dependent => :destroy
  has_many :events, through: :attendees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if current_user
      redirect_to events_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    param = sanitize_params
    @event = Event.new(param)
    @event.start_date = getDate(param)
    if @event.save
      flash[:success] = "Event created successfully"
      redirect_to events_path
    else
      flash.now[:error] = @event.errors.full_messages.join(',')
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    event = Event.find params[:id]
    event.destroy
    flash[:success] = "Event deleted successfully"
    redirect_to events_path
  end

  def edit
  end

  def reject
    event = Attendee.find_by(user_id: current_user, event_id: params[:id])
    if event && event.destroy
      flash[:success] = "Event rejected successfully"
      redirect_to events_path
    else
      flash.now[:error] = "something went wrong" 
      render :index
    end
  end

  def accept
    event = current_user.attendees.new(event_id: params[:id])
    if event.save
      flash[:success] = "Event accepted successfully"
      redirect_to events_path
    else
      flash.now[:error] = "something went wrong" 
      render :index
    end
  end

  private
   def sanitize_params
      params.require(:event).permit(:title, :price, :venue, :start_date)
   end

   def getDate event
      dateObj = %w(1 2 3 4).map { |e| event["start_date(#{e}i)"].to_i }
      data = Date.new *dateObj
   end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_sign_up_params, only: [:create]

  def new
    super
  end

  def create
    super
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name, :gender])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/events_helper.rb
module EventsHelper
  
  def is_register event
    current_user.events.where(id: event.id)[0]
  end

  def is_avtive event
    event.start_date.future?
  end

  def get_price price
    if current_user.gender == 'Female'
      html = "<del> #{price}</del>&nbsp;&nbsp&nbsp;&nbsp;#{(price.to_f * 0.95).round(2)}"
    else
      html = "<span> #{price} </span>"
    end
  end
end

app/views/dashboard/index.html.erb
<% if current_user %>
  <%= render "shared/header" %>
<% else %>
  <div class='content'>
    <div class='title'> Welcome to Event Ticking system </div>
    <div class='img'>
      <img src="<%= image_path 'images.jpeg' %>"  alt='image'>
    </div> 
    <div class='dis'>
      Welcome Sam to Event Ticking system </br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
      esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
    </div>
    <div class='rectangle'> <%= link_to "Sign Up", new_user_registration_path  %> </div>
    <div class='rectangle'> <%= link_to "Sign In", new_user_session_path  %> </div>
  </div>
<% end %>

app/views/events/index.html.erb
<%= render "shared/header" %>
<div class="event">
  <div class=title>Event List</div>
  <ul style="background-color: #c9e8c9">
    <li class="flex-2">Title<li>
    <li class="flex-1">Price<li>
    <li class="flex-1">Date<li>
    <li class="flex-1">Venue<li>
    <li class="flex-1">Info<li>
    <li class="button flex-1">-<li>
  </ul>
  <% @event.each do |event| %>
    <ul>
      <li class="flex-2"><%= event.title %><li>
      <li class="flex-1 tooltip">$<%= get_price(event.price).html_safe%>
        <span class="tooltiptext">5% off for female members</span>
      <li>
      <li class="flex-1"><%= event.start_date.strftime("%F") %><li>
      <li class="flex-1"><%= event.venue %><li>
      <li class="flex-1"><%= link_to('View', { action: :show, id: event.id }, method: :get) %></li>
      <% if current_user.role == 'admin' %>
        <li class="button flex-1">
          <%= link_to('Delete', { action: :destroy, id: event.id }, method: :delete) %>
        </li>
      <% else %>
        <% if is_avtive event %>
          <% if is_register event%>
            <li class="button secondry flex-1">  <%= link_to('Reject', { action: :reject, id: event.id }, method: :delete) %></li>
          <% else%>
            <li class="button primary flex-1"> <%= link_to('Accept', { action: :accept, id: event.id }, method: :post) %></li>
          <%end%>
        <%else%>
          <li class="button info flex-1">Expired</li>
        <%end%>
      <%end%>
    </ul>
<%end%>
</div>

app/views/events/new.html.erb
<%= render "shared/header" %>
<div class="login-modal">
  <div class="title"> Create Event</div>
  <%= form_with(model: @event, url: "/events", method: "post", local: true) do |f|%>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :start_date %><br />
      <%= f.datetime_select :start_date, ampm: true, order: [:day, :month, :year], start_year: 2020 %>
    </div>

    <div class="field">
      <%= f.label :price %><br />$
      <%= f.number_field :price, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :venue %><br />
      <%= f.text_field :venue, autocomplete: "email" %>
    </div>

    <div class="actions">
      <%= f.submit "Add Event", :class => 'button'%>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<%= render "shared/header" %>
<div>
  <h3>Event Details</h3>
  <ul>
    <li>Title: <%= @event.title%></li>
    <li>Date: <%= @event.start_date.strftime("%F")%></li>
    <li>Price $: <%= get_price(@event.price).html_safe%></li>
    <li>Venue: <%= @event.venue%></li>
    <li>Totle Number of geuest: <%= @event.users.count %></li>
  </ul>
  <div>Guest List </div>
  <% @event.users.each do |user| %>
    <ul>
      <li>
        <span style="margin-right: 50px"> <%= user.name %></span>
        <span> <%= user.gender %></span>
      </li> 
    </ul>
  <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <ul>
    <li class="logo">
      <img src="<%= image_path 'Webp.net-resizeimage.jpg' %>"alt='image'>
    </li> 
    <li class="text"><%= link_to('Event', root_path) %></li>
    <li>Welcome <%= current_user.name %></li>
    <% if current_user.role == 'admin'%>
      <li><%= link_to(' Create Event', new_event_path) %> </li>
    <% end %>
    <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
  </ul>
</div>
<% flash.each do |type, msg| %>
  <div class="alert">
    <div class="alert-<%=type%>"> <%= msg %></div>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_sign_in_page.erb
<div class="login-modal">
  <div class="title"> Sign In</div>
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "current-password" %>
    </div>

    <div class="actions">
      <%= f.submit "Log in", :class => 'button'%>
    </div>
  <% end %>
</div>

app/views/users/shared/_sign_up_page.html.erb
<div class="login-modal">
  <div class="title"> Sign Up</div>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :Gender %>
      <%= f.select :gender, ['Male', 'Female'] %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up", :class => 'button'%>
    </div>
  <% end %>
</div>